In [28]:
import os
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [29]:
df_rsa = pd.read_csv('df_rsa.csv')
df_rsa

,Unnamed: 0,src_subject_id,subjectkey,interview_age,sex,eventname,mri_info_deviceserialnumber,scannerID
0,8,NDAR_INV0VXEC29A,NDAR_INV0VXEC29A,125,F,baseline_year_1_arm_1,HASH5ac2b20b,1
1,20,NDAR_INVXWXUUU18,NDAR_INVXWXUUU18,109,M,baseline_year_1_arm_1,HASH69f406fa,2
2,70,NDAR_INVZ4NNCTMH,NDAR_INVZ4NNCTMH,125,F,baseline_year_1_arm_1,HASH1314a204,3
3,75,NDAR_INVKT7E0NA1,NDAR_INVKT7E0NA1,131,M,baseline_year_1_arm_1,HASH4b0b8b05,4
4,78,NDAR_INV20CZ5PTX,NDAR_INV20CZ5PTX,130,M,baseline_year_1_arm_1,HASHdb2589d4,5
...,...,...,...,...,...,...,...,...
5007,18302,NDAR_INV1EGW0J5N,NDAR_INV1EGW0J5N,109,M,baseline_year_1_arm_1,HASHb640a1b8,7
5008,18304,NDAR_INV2F729N9A,NDAR_INV2F729N9A,117,F,baseline_year_1_arm_1,HASHc3bf3d9c,16
5009,18305,NDAR_INVMAW066K7,NDAR_INVMAW066K7,120,F,baseline_year_1_arm_1,HASH96a0c182,10
5010,18314,NDAR_INV5DJB8FFX,NDAR_INV5DJB8FFX,114,F,baseline_year_1_arm_1,HASH5ac2b20b,1
5011,18316,NDAR_INV19BR9YHW,NDAR_INV19BR9YHW,111,F,baseline_year_1_arm_1,HASH3935c89e,17

In [30]:
df = pd.read_csv('./Data/ABCD-behav/abcd_ps01.csv',low_memory=False)
df = df.iloc[df['eventname'].values=='baseline_year_1_arm_1']
df = df.iloc[1::]

In [35]:
iq = [df.iloc[df['subjectkey'].values==sub]['pea_wiscv_trs'].values[0] for sub in df_rsa['subjectkey'].values]

In [42]:
df_rsa['IQ'] = iq
df_rsa['IQ'] = pd.to_numeric(df_rsa['IQ']).values

In [44]:
df_rsa.to_csv('df_rsa.csv')

In [45]:
df_rsa

,Unnamed: 0,src_subject_id,subjectkey,interview_age,sex,eventname,mri_info_deviceserialnumber,scannerID,IQ
0,8,NDAR_INV0VXEC29A,NDAR_INV0VXEC29A,125,F,baseline_year_1_arm_1,HASH5ac2b20b,1,19.0
1,20,NDAR_INVXWXUUU18,NDAR_INVXWXUUU18,109,M,baseline_year_1_arm_1,HASH69f406fa,2,20.0
2,70,NDAR_INVZ4NNCTMH,NDAR_INVZ4NNCTMH,125,F,baseline_year_1_arm_1,HASH1314a204,3,18.0
3,75,NDAR_INVKT7E0NA1,NDAR_INVKT7E0NA1,131,M,baseline_year_1_arm_1,HASH4b0b8b05,4,17.0
4,78,NDAR_INV20CZ5PTX,NDAR_INV20CZ5PTX,130,M,baseline_year_1_arm_1,HASHdb2589d4,5,13.0
...,...,...,...,...,...,...,...,...,...
5007,18302,NDAR_INV1EGW0J5N,NDAR_INV1EGW0J5N,109,M,baseline_year_1_arm_1,HASHb640a1b8,7,20.0
5008,18304,NDAR_INV2F729N9A,NDAR_INV2F729N9A,117,F,baseline_year_1_arm_1,HASHc3bf3d9c,16,20.0
5009,18305,NDAR_INVMAW066K7,NDAR_INVMAW066K7,120,F,baseline_year_1_arm_1,HASH96a0c182,10,21.0
5010,18314,NDAR_INV5DJB8FFX,NDAR_INV5DJB8FFX,114,F,baseline_year_1_arm_1,HASH5ac2b20b,1,19.0
5011,18316,NDAR_INV19BR9YHW,NDAR_INV19BR9YHW,111,F,baseline_year_1_arm_1,HASH3935c89e,17,12.0

In [47]:
np.isnan(df_rsa['IQ'].values).sum()

103